# CityBrain V7.3 one-click demo runner for Windows PowerShell
# ASCII-only text to avoid Windows PowerShell encoding issues.
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\RUN_DEMO_WINDOWS.ps1
#   powershell -ExecutionPolicy Bypass -File .\RUN_DEMO_WINDOWS.ps1 -Mode Emulator
#   powershell -ExecutionPolicy Bypass -File .\RUN_DEMO_WINDOWS.ps1 -Ip 192.168.0.23
#   powershell -ExecutionPolicy Bypass -File .\RUN_DEMO_WINDOWS.ps1 -NoServer

param(
    [ValidateSet("Phone", "Emulator")]
    [string]$Mode = "Phone",
    [string]$Ip = "",
    [int]$Port = 8000,
    [switch]$NoServer
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Backend = Join-Path $Root "backend"
$AndroidGradleProps = Join-Path $Root "android\gradle.properties"

function Get-DemoIPv4 {
    $candidates = Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object {
            $_.IPAddress -notlike "169.*" -and
            $_.IPAddress -ne "127.0.0.1" -and
            $_.PrefixOrigin -ne "WellKnown" -and
            $_.InterfaceAlias -notmatch "Loopback|Virtual|VMware|VirtualBox|vEthernet|Bluetooth|Docker|WSL"
        }

    $preferred = $candidates |
        Where-Object { $_.InterfaceAlias -match "Wi-Fi|WLAN|Wireless|Ethernet" } |
        Select-Object -First 1

    if ($preferred) { return $preferred.IPAddress }

    $fallback = $candidates | Select-Object -First 1
    if ($fallback) { return $fallback.IPAddress }

    throw "IPv4 address not found. Connect PC and phone to the same Wi-Fi, or pass -Ip manually. Example: -Ip 192.168.0.23"
}

function Write-GradleProps([string]$BaseUrl) {
@"
# Auto-generated by CityBrain V7.3 RUN_DEMO_WINDOWS.ps1
# Emulator: http://10.0.2.2:$Port/
# Physical phone on same Wi-Fi: http://<PC_IPV4>:$Port/
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1536m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
android.overridePathCheck=true
CITYBRAIN_BASE_URL=$BaseUrl
"@ | Set-Content -Encoding UTF8 $AndroidGradleProps
}

if ($Mode -eq "Emulator") {
    $BaseUrl = "http://10.0.2.2:$Port/"
    $PhoneUrl = "http://127.0.0.1:$Port/"
} else {
    if ([string]::IsNullOrWhiteSpace($Ip)) { $Ip = Get-DemoIPv4 }
    $BaseUrl = "http://$Ip`:$Port/"
    $PhoneUrl = $BaseUrl
}

Write-GradleProps $BaseUrl

Write-Host ""
Write-Host "[CityBrain V7.3] Server address configured" -ForegroundColor Green
Write-Host "Mode            : $Mode" -ForegroundColor DarkGray
Write-Host "Student Web     : http://127.0.0.1:$Port/" -ForegroundColor Cyan
Write-Host "Admin Web       : http://127.0.0.1:$Port/admin/login" -ForegroundColor Cyan
Write-Host "Phone Web       : $PhoneUrl" -ForegroundColor Yellow
Write-Host "Android BASE_URL: $BaseUrl" -ForegroundColor Yellow
Write-Host "Gradle Props    : $AndroidGradleProps" -ForegroundColor DarkGray
Write-Host "Android Studio  : Open android/ folder, Sync Project, then Run" -ForegroundColor Magenta
Write-Host ""

if ($NoServer) {
    Write-Host "NoServer option enabled. Server will not be started." -ForegroundColor Yellow
    exit 0
}

Set-Location $Backend

if (-not (Test-Path ".venv")) {
    py -3 -m venv .venv
}

. .\.venv\Scripts\Activate.ps1
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
python -m uvicorn app.main:app --host 0.0.0.0 --port $Port --reload
