# CityBrain V8 Android BASE_URL setter for Windows PowerShell
# ASCII-only file to avoid encoding issues.
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\scripts\set_android_base_url_windows.ps1
#   powershell -ExecutionPolicy Bypass -File .\scripts\set_android_base_url_windows.ps1 -Mode Emulator
#   powershell -ExecutionPolicy Bypass -File .\scripts\set_android_base_url_windows.ps1 -Ip 192.168.0.23

param(
    [ValidateSet("Phone", "Emulator")]
    [string]$Mode = "Phone",
    [string]$Ip = "",
    [int]$Port = 8000
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$GradleProps = Join-Path $Root "android\gradle.properties"

function Get-DemoIPv4 {
    $candidates = Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object {
            $_.IPAddress -notlike "169.*" -and
            $_.IPAddress -ne "127.0.0.1" -and
            $_.PrefixOrigin -ne "WellKnown" -and
            $_.InterfaceAlias -notmatch "Loopback|Virtual|VMware|VirtualBox|vEthernet|Bluetooth|Docker|WSL"
        }

    $preferred = $candidates |
        Where-Object { $_.InterfaceAlias -match "Wi-Fi|WLAN|Wireless|Ethernet" } |
        Select-Object -First 1

    if ($preferred) { return $preferred.IPAddress }

    $fallback = $candidates | Select-Object -First 1
    if ($fallback) { return $fallback.IPAddress }

    throw "IPv4 address not found. Connect PC and phone to the same Wi-Fi, or pass -Ip manually. Example: -Ip 192.168.0.23"
}

if ($Mode -eq "Emulator") {
    $BaseUrl = "http://10.0.2.2:$Port/"
} else {
    if ([string]::IsNullOrWhiteSpace($Ip)) { $Ip = Get-DemoIPv4 }
    $BaseUrl = "http://$Ip`:$Port/"
}

@"
# Auto-generated by scripts/set_android_base_url_windows.ps1
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1536m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
android.overridePathCheck=true
CITYBRAIN_BASE_URL=$BaseUrl
"@ | Set-Content -Encoding UTF8 $GradleProps

Write-Host "Android BASE_URL set to $BaseUrl" -ForegroundColor Green
Write-Host "Open Android Studio > Sync Project > Run" -ForegroundColor Cyan
